frr version 8.4
frr defaults traditional
hostname r3
service integrated-vtysh-config
ipv6 forwarding

router bgp 1
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast

 neighbor 2001:db8:35::5 remote-as 3
 neighbor 2001:db8:23::2 remote-as 1
 neighbor 2001:db8:34::4 remote-as 1

 address-family ipv6 unicast
  network 2001:db8:1::3/128
  neighbor 2001:db8:35::5 activate
  neighbor 2001:db8:23::2 activate
  neighbor 2001:db8:34::4 activate
  neighbor 2001:db8:35::5 next-hop-self
  neighbor 2001:db8:23::2 next-hop-self
  neighbor 2001:db8:34::4 next-hop-self
 exit-address-family

line vty