frr version 8.4
frr defaults traditional
hostname r6
service integrated-vtysh-config
ipv6 forwarding

router bgp 4
 bgp router-id 6.6.6.6
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast

 neighbor 2001:db8:46::4 remote-as 1

 address-family ipv6 unicast
  network 2001:db8:1::6/128
  neighbor 2001:db8:46::4 activate
  neighbor 2001:db8:46::4 next-hop-self
 exit-address-family

line vty