frr version 8.4
frr defaults traditional
hostname r2
service integrated-vtysh-config
ipv6 forwarding

router bgp 1
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast

 neighbor 2001:db8:12::1 remote-as 2
 neighbor 2001:db8:23::3 remote-as 1
 neighbor 2001:db8:24::4 remote-as 1

 address-family ipv6 unicast
  network 2001:db8:1::2/128
  neighbor 2001:db8:12::1 activate
  neighbor 2001:db8:12::1 next-hop-self
  neighbor 2001:db8:23::3 activate
  neighbor 2001:db8:23::3 next-hop-self
  neighbor 2001:db8:24::4 activate
  neighbor 2001:db8:24::4 next-hop-self
 exit-address-family

line vty