frr version 8.4
frr defaults traditional
hostname r5
service integrated-vtysh-config
ipv6 forwarding

router bgp 3
 bgp router-id 5.5.5.5
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast

 neighbor 2001:db8:35::3 remote-as 1
 neighbor 200.0.0.6 remote-as 4

address-family ipv4 unicast
  neighbor 200.0.0.6 activate
  neighbor 200.0.0.6 next-hop-self
exit-address-family

#  address-family ipv6 unicast
#   network 2001:db8:1::5/128
#   neighbor 2001:db8:35::3 activate
#   neighbor 2001:db8:35::3 next-hop-self
#  exit-address-family

line vty