frr version 8.4
frr defaults traditional
hostname r1
service integrated-vtysh-config
ipv6 forwarding

router bgp 2
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast

 neighbor 2001:db8:12::2 remote-as 1

 address-family ipv6 unicast
  network 2001:db8:1::1/128
  neighbor 2001:db8:12::2 activate
  neighbor 2001:db8:12::2 next-hop-self
 exit-address-family

line vty