frr version 8.4
frr defaults traditional
hostname r1
service integrated-vtysh-config
ipv6 forwarding

router bgp 2
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast

 neighbor 100.0.0.1 remote-as 1

#  address-family ipv4 unicast
#   network 192.168.1.1/32
#   neighbor 100.0.0.1 activate
#   neighbor 100.0.0.1 next-hop-self
#  exit-address-family

line vty