LAB_DESCRIPTION="A medium kathara example of a BGP lab with IPv6"
LAB_NAME="bgp_ipv6_lab"
LAB_EMAIL=noahvanhorenbeke@gmail.com
LAB_AUTHOR="Noah Van Horenbeke"
r1[ipv6]="false"
r1[0]="A"
r1[image]="kathara/frr"

r2[ipv6]="true"
r2[0]="A"
r2[1]="D"
r2[2]="E"
r2[image]="kathara/frr"

r3[ipv6]="true"
r3[0]="B"
r3[1]="D"
r3[2]="F"
r3[image]="kathara/frr"

r4[ipv6]="true"
r4[0]="C"
r4[1]="E"
r4[2]="F"
r4[image]="kathara/frr"

r5[ipv6]="true"
r5[0]="B"
r5[image]="kathara/frr"

r6[ipv6]="true"
r6[0]="C"
r6[image]="kathara/frr"

